#:schema https://api.nuon.co/v1/general/config-schema?type=kubernetes-manifest

name         = "db_secrets"
type         = "kubernetes_manifest"
dependencies = ["postgres"]

namespace = "spookycandy"
manifest = """
# Secret for candy app database connection
apiVersion: v1
kind: Secret
metadata:
  name: candy-db-secret
  namespace: spookycandy
type: Opaque
stringData:
  NEON_DATABASE_URL: "postgresql://{{.nuon.inputs.inputs.db_user}}:{{.nuon.inputs.inputs.db_password}}@postgresql.spookycandy.svc.cluster.local:5432/{{.nuon.inputs.inputs.db_name}}?sslmode=disable"
"""
