apiVersion: v1
kind: Service
metadata:
  name: spooky-candy-app
  namespace: {{ .Values.namespace }}
  labels:
    app: spooky-candy-app
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: spooky-candy-app
