type        = "aws-cloudformation"
name        = "spooky-candy-{{.nuon.install.id}}"
description = "Spooky Candy Manager EKS Install for {{.nuon.install.id}}"

# nested stack - using standard EKS sandbox
vpc_nested_template_url    = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.1.8/vpc/eks/default/stack.yaml"
runner_nested_template_url = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.1.8/runner/asg/stack.yaml"
